[[main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1.0
[[main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 2.0
[[main]]
identifier = "news"
name = "News"
url = "/news"
weight = 4.0
