style = "green"
logo = "/image/logo.png"
logo_small = "/image/logo.png"
about_us = """Acme Corporation is world's leading manufacturer of digital shapes. 
  From squares and circles to triangles and hexagons, we have it all. 
  Browse through our collection of various forms with different thickness and line styles. 
  We shape the world. You live in it."""
color = "#71B180"
copyright = "Acme corporation"
    [[footer]]
    title = "About"
    content = "Acme Corporation is the world's leading manufacturer of digital shapes. From squares and circles to triangles and hexagons, we have it all. Browse through our collection of various forms with different thickness and line styles. We shape the world. You live in it."

    [[footer]]
    title = "Recent blog posts"
    recents = "blog"
    recentCount = 7.0

    [[footer]]
    title = "Contact Us"
    contact = true
    
    [[footer]]
    title = "Important Links"
    menu = true
[recent_posts]
enable = true
